server:
  port: 8072

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false  # switch to true for automatic routing
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 10

logging:
  level:
    gr:
      georgestaav:
        gatewayserver: info
    org:
      springframework:
        cloud:
          gateway: warn

